# Generated by Django 5.2.3 on 2025-06-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_image_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_reported',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='report_reason',
            field=models.CharField(blank=True, choices=[('inappropriate', 'Inappropriate language'), ('spam', 'Spam or promotion'), ('fake', 'Fake or dishonest review'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
