# Generated by Django 5.2.3 on 2025-06-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productreview_is_reported_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
