# Generated by Django 5.2.3 on 2025-07-01 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_id', models.FileField(blank=True, null=True, upload_to='driver_documents/proof_of_id/')),
                ('right_to_work', models.FileField(blank=True, null=True, upload_to='driver_documents/right_to_work/')),
                ('vehicle', models.FileField(blank=True, null=True, upload_to='driver_documents/vehicle/')),
                ('business_insurance', models.FileField(blank=True, null=True, upload_to='driver_documents/business_insurance/')),
                ('thermal_insulation_kit', models.FileField(blank=True, null=True, upload_to='driver_documents/thermal_insulation_kit/')),
                ('safety_training', models.FileField(blank=True, null=True, upload_to='driver_documents/safety_training/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_description', models.TextField()),
                ('shop_email', models.EmailField(max_length=254)),
                ('shop_contact_number', models.CharField(max_length=20)),
                ('flat_house_number', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='seller.shopcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_id', models.FileField(blank=True, null=True, upload_to='documents/proof_of_id/')),
                ('right_to_work', models.FileField(blank=True, null=True, upload_to='documents/right_to_work/')),
                ('food_business_registration', models.FileField(blank=True, null=True, upload_to='documents/food_business_registration/')),
                ('hmrc_tax_reference', models.FileField(blank=True, null=True, upload_to='documents/hmrc_tax_reference/')),
                ('allergen_training', models.FileField(blank=True, null=True, upload_to='documents/allergen_training/')),
                ('waste_management', models.FileField(blank=True, null=True, upload_to='documents/waste_management/')),
                ('safety_management', models.FileField(blank=True, null=True, upload_to='documents/safety_management/')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='seller.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller.shop')),
            ],
        ),
    ]
