# Generated by Django 5.2.3 on 2025-06-17 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_id', models.FileField(blank=True, null=True, upload_to='driver_documents/proof_of_id/')),
                ('right_to_work', models.FileField(blank=True, null=True, upload_to='driver_documents/right_to_work/')),
                ('vehicle', models.FileField(blank=True, null=True, upload_to='driver_documents/vehicle/')),
                ('business_insurance', models.FileField(blank=True, null=True, upload_to='driver_documents/business_insurance/')),
                ('thermal_insulation_kit', models.FileField(blank=True, null=True, upload_to='driver_documents/thermal_insulation_kit/')),
                ('safety_training', models.FileField(blank=True, null=True, upload_to='driver_documents/safety_training/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
