# Generated by Django 5.2.3 on 2025-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='categories',
            field=models.ManyToManyField(blank=True, to='seller.shopcategory'),
        ),
    ]
